version: "3.9"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final
    image: bloomingtec/todo-api:dev
    container_name: bloomingtec-todo-api-dev
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - BASIC_USER=${BASIC_USER:-admin}
      - BASIC_PASS=${BASIC_PASS:-password}
      - ConnectionStrings__DefaultConnection=Data Source=/data/todo.db
      - DOTNET_RUNNING_IN_CONTAINER=true
    ports:
      - "5000:8080"
    volumes:
      - todo-data:/data
      - ./src:/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - todo-dev-network

volumes:
  todo-data:
    driver: local

networks:
  todo-dev-network:
    driver: bridge
